services:
  frontend:
    build:
      context: ./frontend
      target: softwaredesign-frontend
    depends_on:
      backend:
        condition: service_started

  backend:
    build:
      context: ./backend
      target: softwaeredesign-backend
    environment:
      SPRING_PROFILES_ACTIVE: prod
      LOGGING_LEVEL_FI_TUNI_SOFTWAREDESIGN: INFO
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - redis

  redis:
    image: redis:7.0
    container_name: softwaredesign-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_started

volumes:
  redis-data:
