spring.application.name=softwaredesign

server.error.include-stacktrace=never

yelp.api.key=YELP_API_KEY

spring.cache.type=redis
spring.redis.host=${SPRING_REDIS_HOST}
spring.redis.port=${SPRING_REDIS_PORT}