name: Backend CI

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "backend/**"
  push:
    branches:
      - dev
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"

      - name: Build and test
        run: ./mvnw clean verify
