name: Frontend CI

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "frontend/**"
  push:
    branches:
      - dev
    paths:
      - "frontend/**"

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20 LTS
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Prettier (check)
        run: npm run prettier:check

      - name: ESLint
        run: npm run lint
        # If you want to fail build on warnings:
        # run: npm run lint -- --max-warnings=0

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20 LTS
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
